### ISSUE TITLE
Add DynamicCastSafe or similar method

### ISSUE THREAD

**Issue by dotnetchris** [tompazourek/Endless#52]
Usage would be same as DynamicCast but it would only return values that it can safely cast (probably using type IsAssignableFrom or similar)

This would replace 

list.OfType<Foo>().Cast<Foo>()

**Comment by dotnetchris** [comment]
Actually this isnt' the exact use case i was thinking of, I can't remember when OfType isn't sufficient but i know i've found it before

**Comment by tompazourek** [comment]
Interesting. If you find it, please tell me. :+1:
