### ISSUE TITLE
Support for Portable Class Libraries

### ISSUE THREAD

**Issue by R2D221** [tompazourek/Endless#54]
I really like this library, it seems great for my project. However, I need it as a PCL so that I can include it in Windows Phone and Xamarin.

**Comment by tompazourek** [comment]
Hi R2D221, thanks for your interest :)

I don't have much experience with regard to building PCLs. If you do, feel free to make a pull request.

When I have some more time, I might consider experimenting with the PCL build.

**Comment by tompazourek** [comment]
Closing, the 0.7.0-alpha1 version now supports .NET Standard 1.1.
